image: node:24

default:
  interruptible: true
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/

stages:
  - test
  - build
  - publish

test:
  stage: test
  timeout: 5 minutes
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - npm run test

build-web:
  stage: build
  timeout: 10 minutes
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  dependencies:
    - test
  script:
    - npm ci
    - npm run build
    - cp dist/index.html dist/404.html
  artifacts:
    expire_in: 3 hours
    paths:
      - dist/

publish-web:
  image: alpine
  stage: publish
  before_script:
    - 'which ssh-agent || ( apk add --update openssh )'
    - apk add --update bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    # Install rsync
    - apk add rsync
    - rsync --version
  timeout: 5 minutes
  rules:
    - if: $CI_COMMIT_TAG =~ /^kubo-v\d+\.\d+\.\d+$/
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  dependencies:
    - build-web
  environment:
    name: demo.kubo.watch
    url: https://demo.kubo.watch
  script:
    - rsync -avz --delete -e ssh dist/. weboftrustfoundation_9rsu0j7cylw@demo.kubo.watch:/var/www/vhosts/weboftrustfoundation.org/demo.kubo.watch
    - echo "----------------------------------------------------------------------"
    - echo "Deployment ready (tag "$CI_COMMIT_TAG"), check https://demo.kubo.watch"
    - echo "----------------------------------------------------------------------"